### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by davideastmond** [chingu-voyages/v51-tier3-team-35#23]
**User Story Description**
As a user in an adventure canvas, I want to create different `accommodation` `travel` `dining` and `activity` occurrences (cards) at a specific date-Time so that I can plan specific things in the trip. 
As a user I want to make comments on the card

**Steps to Follow (optional)**

- [x] Step (1) Create cards that can hold the data relavent to the occurrence typpe. Card should be clickable and draggable (move them around on the schedule calendar).  
- [x] #45

- [x] Step (2) Create comments UI - simple comment chain allowing user to post comment with date, time and username tagged
- [x] Step (3) Create API end point and data structures that handle inserting occurrences 
- [x] Step (4) Create API end point and data structures that handle comments
- [x] Step (5) Setup and configure our geoLoc API (Google maps API?)
- [ ] #46

Additional Considerations
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

** __Acceptance Criteria__ **
- User can create occurrence cards
- User can delete cards
- User can create comments
- User can view comments
- Maps Api data is rendered 
- Event populator data is working properly

**Comment by LootingMonk** [comment]
https://docs.google.com/document/d/1Y8zUJQyK1Szu-4sBaL4252YHoXfTfLAW2GaTL2leqjQ/edit
