### ISSUE TITLE
Adventure Canvas

### ISSUE THREAD

**Issue by davideastmond** [chingu-voyages/v51-tier3-team-35#25]
**User Story Description**
As a user with a shared adventure link
I want to able to view my adventure calendar

Steps to Follow (optional)

- [x] Step (1) Create the canvas calendar with time(Y-axis) and date of the week (X -axis) with the ability to scroll on through the calendar grid.

- [x] Step (2) Create a toolbar when you can select your travel time, dinning etc and drop it on the calendar for all to see.

- [x] Step (3) Render the data from the backend

Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

** Acceptance Criteria **

Users can navigate to the URL
A blank canvas or a canvas populated with up-to-date data is rendered to all users accessing the link
The canvas UI appears

**Comment by LootingMonk** [comment]
https://docs.google.com/document/d/1Y8zUJQyK1Szu-4sBaL4252YHoXfTfLAW2GaTL2leqjQ/edit
